### ISSUE TITLE
grid_description.yaml missing from modelgrids.tar.gz (?)

### ISSUE THREAD

**Issue by pmaxted** [vosjo/speedyfit#5] opened 2022-01-28 15:25 UTC
I have followed the installation instructions at https://speedyfit.readthedocs.io/en/stable/userguide/install.html 

I get the following error.

```
$ speedyfit checkgrids 
Checking which atmosphere models are available... 
Checking for models in /home/jovyan/modelgrids 
grid_description.yaml file not found or no models included in the description file. 
Please add a grid_description.yaml file in the SPEEDYFIT_MODELS directory.
``` 

Should the file `grid_description.yaml` be included with `modelgrids.tar.gz`?

**Comment by vosjo** [comment] 2022-02-19 15:53
I assume based on you other issue that this was caused by the trailing / error. If so it should be fixed using the new release. 
If there is still a problem, let me know.

**Closed** 2022-02-24 11:50 UTC
